### ISSUE TITLE
Add LICENSE file to the repository

### ISSUE THREAD

**Issue by iblech** [pbelmans/gerby-website#117]
It'd be good to know which license applies to this project. I can take off the hassle of adding the appropriate file and adding a remark on the gerby website, by preparing a suitable pull request, but it's obviously your call to decide on which license to use! (Affero GPLv3?)

**Comment by pbelmans** [comment]
I have to admit I'm bad at understanding license-related things. I'll ping @aisejohan, as he knows more about this.

In any case, Gerby should have an open license, which on the other hand shouldn't force derivatives (such as the future Kerodon) to share their code and design.

**Comment by aisejohan** [comment]
OK, we could use the 3-clause BSD license which is being used by Flask and by Jinja2. Plastex uses the even more permissive MIT/X11 license which would also be fine for us.

Affero GPLv3 doesn't work because of what Pieter said: even templates and css files would be considered derivative works, so this *really* wouldn't work. As far as I understand it, with GPLv2 or GPLv3 you can still run a website with modified code without having to disclose the code (this is the raison d'etre of Affero) but you cannot distribute it (as a software package) without also disclosing the code.

I'm somewhat in favor of using a more permissible license and just trying to get people or organizations to contribute back into gerby project by giving convincing arguments as to why they should do so.

@pbelmans: Since you wrote almost all the code, it is your decision. You can add the license by just a few clicks on the github interface.

**Comment by ttmc** [comment]
I'd like to use Gerby for an upcoming project, but I can't use it unless it has a clear license.

For starters, the root directory of this repo should have a license file (such as `LICENSE.rst`, for example). Just find another repo with the license you want, and copy its license file to this repo. Here's Flask's license file, for example:

https://github.com/pallets/flask/blob/main/LICENSE.rst

**Comment by pbelmans** [comment]
There's now an MIT license in place, that should settle things I think?

Good luck with using Gerby!
