### ISSUE TITLE
Use titles in <title>

### ISSUE THREAD

**Issue by pbelmans** [pbelmans/gerby-website#123]
For example, the page https://stacks.math.columbia.edu/tag/02KH could be titled *Tag 02KH: Flat base change---The Stacks project*.

One needs to be careful about mathematics and other TeX in the title.

Right now Google calls the search result for `flat base change` *(Flat base change)*, which looks a bit silly.

**Comment by pbelmans** [comment]
Without a good way of stripping all TeX this won't be possible: it's the same reason as why one needs `\texorpdfstring` after all.

**Comment by iblech** [comment]
Just a remark, simply rendering TeX code as plain text might be good enough to provide proper `<title>`s for most tags, even if it's of course not perfect. A title like `Tag 1234: Points of the small \'etale site---Stacks Project` might still be better than the plain `Tag 1234---Stacks Project`.

To gauge how bad this ASCII fallback would be in case of the Stacks Project, I just did a quick grep over all sections and subsections. It turns out that we use TeX commands in section and subsection titles for only one purpose, namely accents like in `\'etale topology`, `{\v C}ech complex`, `K\"unneth formula`. If desired, we could even hack together support for these particular uses.
