### ISSUE TITLE
Items again

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#129]
OK, I am just now fixing a few left over cases of having mathematics inside item labels in itemize or enumerate environments. Doing this I found a small issue with [Tag 03JX](https://stacks.math.columbia.edu/tag/03JX). There the underlying latex has `\item[]` but the website shows a bullet. Not sure if this should be an issue against plastex... Also very low priority.

**Comment by pbelmans** [comment]
For Kerodon we are using the `description` environment for these things, as using `itemize` for this is somewhat an abuse of the environment. The problem is that LaTeX deals with (un)ordered lists differently from HTML. Maybe this would be an option for the Stacks project too? You can see this in action on https://kerodon.net/tag/002H.

**Comment by aisejohan** [comment]
Sorry, I don't think I want to use the description environment since it seems to be giving me a `:` in the output in the pdf (just tried quickly). But I am closing this now as it is so unimportant.
