### ISSUE TITLE
Make the sidebar fixed (scroll, then fixed) just like the breadcrumb

### ISSUE THREAD

**Issue by pbelmans** [pbelmans/gerby-website#20]
I tried to implement this in a clean way, but failed.

**Comment by dkrashen** [comment]
I think I implemented this -- check and see if it is what you are thinking (in the new branch sticky-side).

I also adjusted the spacing of the columns a bit.

Incidentally, it seemed that bootstrap was being a little problematic about small spacing issues when using the row and column classes within the section element instead of the divs. I put them in divs in the sticky-side version...

**Comment by pbelmans** [comment]
Thanks, that's exactly the behaviour I was thinking of!

What's the reasoning between the different spacing? The current setup is a bit heavy on the whitespace, was this a conscious decision?

**Comment by dkrashen** [comment]
ahh -- my bad. just put in a version without that extra spacing. it was an artifact of intermediate work!
