### ISSUE TITLE
Names of contributors

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#33]
It kind of would be fun if we could ask contributors for latex expressions for their names, e.g., for chinese names using characters &#26446;&#26102;&#29835; or &#26446;&#26178;&#29835; for my student Shizhang Li. Maybe this should be an issue for stacks/stacks-project instead?

**Comment by pbelmans** [comment]
Unicode would be better. But we can certainly display these somewhere. If it's in Unicode, it should work. Let's decide where to put this next week.

**Comment by aisejohan** [comment]
Of course when I wrote the issue I used `&#26446;&#26102;&#29835;` and `&#26446;&#26178;&#29835;`. Yes let's talk about this later; it is just for fun.

**Comment by pbelmans** [comment]
In any case, we should display a list of contributors. Maybe on the About page too, otherwise people really have to click through to the Contribute page.

Idea: have Unicode Chinese names in the file CONTRIBUTORS between (), and strip these when creating the TeX files, but import these in the database.

**Comment by pbelmans** [comment]
Implemented now.
