### ISSUE TITLE
Print stylesheet in Safari

### ISSUE THREAD

**Issue by pbelmans** [pbelmans/gerby-website#42]
It's not as bad as in #41, but there is a huge right margin.

**Comment by chngr** [comment]
Unfortunately, this, too, seems like a quirk of the browser rather than any deficiency on the part of the print stylesheet. See, for example, the StackOverflow question [How to set Safari print margins via CSS to print borderless](https://stackoverflow.com/questions/13154147/how-to-set-safari-print-margins-via-css-to-print-borderless). (And, generally, just try to print some random page from the interwebs.)

**Comment by pbelmans** [comment]
Great, unfixable browser quirks are my favourite. In that case, we won't have to spend any time on this I guess.
