### ISSUE TITLE
Lists in search preview are messed up

### ISSUE THREAD

**Issue by pbelmans** [pbelmans/gerby-website#88]
The margins are wrong (again), e.g. search for `"is universally exact"`, and click the first result.

Also, the preview icon is now inline with the preview text. Maybe we don't want text to appear under the preview icon? Click on the second (or even better, fourth) result to see what I mean.

**Comment by chngr** [comment]
Looks like we need to make a decision:

  - If we do not want the preview icon inline with the preview text, I think this problem is solved by adding something like a `2em` padding to, say, the `div.preview` class. (It might be good to make this selector even more specific, say in the `bonsai`, etc...); or
  - If we do want the preview icon with the preview text, then changing the left margin for `ol#search-results div.html li:before` from `3.5em` to `2em`, or so, resolves the issue.

I think both things look fine. Though here is perhaps an argument for having the preview icon inline with the text: otherwise, the width of the preview text is quite a bit smaller, and longer equations could overflow or else sentences with longer words will suffer from gross expansion in attempt to reflow things for justified text. Having said that, it does perhaps seem more natural and visually intuitive to have the preview icon hanging by itself.
